language: generic
sudo: required
services:
  - docker
  
before-install:
  - docker build -t tonymall/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tonymall/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-957153670764"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"